[FrameworkBundle] Fix argument not provided to `add_bus_name_stamp_middleware`
The bus name only gets provided to `add_bus_name_stamp_middleware` if
using the default middlewares meaning that if you want to define the
middlewares yourself then you need to define this service or you get
an error:

`Too few arguments to function Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::__construct(), 0 passed`